/*
 * HC_SR04_sensor.c
 *
 *  Created on: Oct 13, 2022
 *      Author: Nada
 */

#include "gpio.h"
#include "HC_SR04_sensor.h"
#include "icu.h"
#include "common_macros.h"
#include <util/delay.h>           /*for the 10 applied by Microcontroller to trigger pulse to the ultrasonic module */

uint8 g_edgeCount = 0;
uint16 g_HighTime = 0;

/*
 * Description :
 * Initialize the Ultrasonic Sensor:
 * 1. Initialize the ICU driver with chosen configurations.
 * 2. Setup the ICU call back function.
 * 3. Configure trigger pin as an output pin.
 */
void Ultrasonic_init(void) {
	Icu_ConfigType Icu_Config = { F_CPU_8, RISING };
	Icu_init(&Icu_Config);
	GPIO_setupPinDirection(TRIGER_PORT_ID, TRIGER_PIN_ID, PIN_OUTPUT);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
}
/*
 * Description :
 * Function to send the Trigger pulse to the ultrasonic sensor for 10 us.
 */

void Ultrasonic_Trigger(void) {
	GPIO_writePin(TRIGER_PORT_ID, TRIGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGER_PORT_ID, TRIGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description : Function that reads the calculated distance
 * 1. Send the Trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start ICU measurements.
 * 3. Calculate and return distance measured.
 */

uint16 Ultrasonic_readDistance(void) {
	uint16 dist = 0;

	Ultrasonic_Trigger();

	while (g_edgeCount != 3)
		; /*To wait for the right distance calculations*/

	dist = (uint16) (g_HighTime / DISTANCE_IN_CM);

	return dist;
}

/*
 * Description : The call back function called by the ICU driver
 * This is used to calculate the pulse time generated by the ultrasonic sensor.
 */

void Ultrasonic_edgeProcessing(void) {
	g_edgeCount++;
	if (g_edgeCount == 1) {
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	} else if (g_edgeCount == 2) {
		/* Store the High time value */
		g_HighTime = Icu_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		/*Flag to check for the correct distance value*/
		g_edgeCount++;
	}
}

