/******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: HC_SR04_sensor.h
 *
 * Description: header file for the HC-SR-04 Ultrasonic Sensor driver
 *
 * Author: Nada
 *
 *******************************************************************************/
#ifndef HC_SR04_SENSOR_H_
#define HC_SR04_SENSOR_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

extern uint8 g_edgeCount; /*global variable shared within program scope*/
#define TRIGER_PORT_ID PORTB_ID
#define TRIGER_PIN_ID PIN5_ID
#define DISTANCE_IN_CM 58.8

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Initialize the Ultrasonic Sensor:
 * 1. Initialize the ICU driver with chosen configurations.
 * 2. Setup the ICU call back function.
 * 3. Configure trigger pin as an output pin.
 */
void Ultrasonic_init(void);

/*
 * Description :
 * Function to send the Trigger pulse to the ultrasonic sensor.
 */

void Ultrasonic_Trigger(void);

/*
 * Description : Function that reads the calculated distance
 * 1. Send the Trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start ICU measurements.
 * 3. Calculate and return distance measured.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description : The call back function called by the ICU driver
 * This is used to calculate the pulse time generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* HC_SR04_SENSOR_H_ */
